[project]
name = "reinforcemol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
   "gymnasium>=1.1.1",
   "rdkit>=2025.3.3",
   "torch>=2.7.1",
   "torch-geometric>=2.6.1",
   "tqdm>=4.67.1",
]
